[default]
timezone = "Asia/Shanghai"
cookies = "<default_cookies>"

[default.envs]
timezone = "Asia/Shanghai"
hello = "Hello"
world = "World"
emojis = ["🤣", "🙃", "🫠"]

[default.mods]
random = "random"
datetime = { type = "module", value = "datetime" }
pytz = { type = "module", value = "pytz" }
two = { type = "expression", value = "1 + 1" }

[default.vars]
now = "mods['datetime'].datetime.now(mods['pytz'].timezone(envs['timezone']) if envs['timezone'] is not None else None)"

[default.jobs.normal]
cron = "0 0/30 * * * *"
jitter = 600
select = "random"
templates = [
    "<1> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][0]}",
    "<2> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][1]}",
    "<3> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][2]}",
    { text = "<4> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {mods['random'].choice(envs['emojis'])}", images = ["http://www.lenna.org/lena_std.tif"] }
]

[default.jobs.double]
cron = "0 0/15 * * * *"
jitter = 300
select = "random"
templates = [
    "[1] Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][0]}",
    "[2] Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][1]}",
    "[3] Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][2]}",
    { text = "[4] Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {mods['random'].choice(envs['emojis'])}", images = ["http://www.lenna.org/lena_std.tif"] }
]

[coder]
cookies = "<coder_cookies>"

[coder.envs]
hello = "World"
world = "Hello"
