[default]
timezone = "Asia/Shanghai"
cookies = "<default_cookies>"

[default.envs]
timezone = "Asia/Shanghai"
hello = "Hello"
world = "World"
emojis = ["🤣", "🙃", "🫠"]
default_options.behavior = "origin"

[default.mods]
random = "random"
operator = "operator"
datetime = { type = "module", value = "datetime" }
pytz = { type = "module", value = "pytz" }
two = { type = "expression", value = "1 + 1" }
current_timezone = { type = "expression", value = "mods['pytz'].timezone(envs['timezone']) if envs['timezone'] is not None else None" }
do_nothing = { type = "expression", value = "lambda: None" }

[default.vars]
now = "mods['datetime'].datetime.now(mods['current_timezone'])"
week = "vars['now'].weekday()"
caches = "{}"

[default.jobs.normal]
cron = "0 0/30 * * * *"
jitter = 600
select = "random"
commands.pre = [
    "mods['operator'].setitem(vars['caches'], 'random_emoji', mods['random'].choice(envs['emojis']))"
]
commands.success = "mods['do_nothing']()"
commands.fail = "mods['do_nothing']()"
commands.post = "mods['do_nothing']()"
templates = [
    "<1> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][0]}",
    "<2> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][1]}",
    "<3> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][2]}",
    { text = "<4> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {vars['caches']['random_emoji']}", images = ["http://www.lenna.org/lena_std.tif"] },
    { text = "<5> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {vars['caches']['random_emoji']}", options.behavior = "origin" },
    { text = "<6> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {vars['caches']['random_emoji']}", options.behavior = "repost", options.keep_quote = true, options.comment = true, options.quote = { uid = "...", bid = "..." } },
    { text = "<7> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {vars['caches']['random_emoji']}", options.behavior = "comment", options.repost = true, options.quote = { uid = "...", bid = "..." } },
    { text = "<8> Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {vars['caches']['random_emoji']}", options = "envs['default_options']" }
]

[default.jobs.double]
cron = "0 0/15 * * * *"
jitter = 300
select = "random"
templates = [
    "[1] Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][0]}",
    "[2] Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][1]}",
    "[3] Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {envs['emojis'][2]}",
    { text = "[4] Now: {vars['now']:%H:%M}, {envs['hello']} {envs['world']}! {mods['random'].choice(envs['emojis'])}", images = "['http://www.lenna.org/lena_std.tif']" }
]

[coder]
cookies.source = "string"
cookies.type = "header"
cookies.value = "<coder_cookies>"

[coder.envs]
hello = "World"
world = "Hello"

[cheems]
cookies.source = "file"
cookies.type = "json"
cookies.value = "<cheems_cookies_json_file>"

[doge]
cookies.source = "file"
cookies.type = "live"
cookies.value = "<doge_live_json_file>"
