FROM python:3.11.5-slim-bookworm

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        chromium \
        chromium-driver \
    ; \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN set -eux; \
    pip install --no-cache-dir -r requirements.txt; \
    rm -rf ./*

ENV TZ="Asia/Shanghai"

ENTRYPOINT ["python", "bot.py", "--real"]
