FROM python:3.11.5-slim-bookworm

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        chromium \
        chromium-driver \
    ; \
    rm -rf /var/lib/apt/lists/*
